// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StatisticsParser.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "StatisticsParser.4A9EFF2E-819B-453D-BE4C-5DF7B343C0E7";
        public const string Name = "Statistics Parser";
        public const string Description = @"Parses STATISTICS IO / STATISTICS TIME output from the SSMS Messages tab and renders it in a dockable tool window. ";
        public const string Language = "en-US";
        public const string Version = "1.0.4";
        public const string Author = "Brent Ozar Unlimited";
        public const string Tags = "SSMS;SQL Server;Statistics IO;Statistics Time;Performance";
        public const bool IsPreview = false;
    }
}
