// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StatisticsParser.Vsix
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidStatisticsParserPackageString = "0f240ee5-54a7-43cb-9710-3a8e2dea5b46";
        public static Guid guidStatisticsParserPackage = new Guid(guidStatisticsParserPackageString);

        public const string guidStatisticsParserCmdSetString = "5b21b934-fb0c-4bec-a466-cdcb423b16e6";
        public static Guid guidStatisticsParserCmdSet = new Guid(guidStatisticsParserCmdSetString);

        public const string queryWindowContextCommandSetString = "33f13ac3-80bb-4ecb-85bc-225435603a5e";
        public static Guid queryWindowContextCommandSet = new Guid(queryWindowContextCommandSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ParseStatisticsGroup = 0x1020;
        public const int cmdidParseStatistics = 0x0100;
        public const int queryWindowContextMenu = 0x0050;
    }
}
